# Generated by Django 4.0 on 2022-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(default=0)),
                ('address', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
