# Generated by Django 4.0 on 2022-02-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('singer_n', models.ManyToManyField(to='ormapp.singer')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
