# Generated by Django 4.0 on 2022-02-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(default='', upload_to='image')),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
